=== wwkkww1983/czmk_proj/CZMK_PROJECT/SecConfig/PermDef.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 4 U (http://www.xmlspy.com) by zhoujin (HollySys) -->
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by  () -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="PublicDef.xsd"/>
	<xs:element name="PermDef">
		<xs:annotation>
			<xs:documentation>子系统权限操作及对象类型定义</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ObjTypeDef">
					<xs:annotation>
						<xs:documentation>对象类型定义</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="ObjType" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
					<xs:unique name="ObjTypeNameUnique">
						<xs:selector xpath="ObjType"/>
						<xs:field xpath="@Name"/>
					</xs:unique>
				</xs:element>
				<xs:element name="OprDef">
					<xs:annotation>
						<xs:documentation>操作定义</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Operation" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
					<xs:unique name="OprNameUnique">
						<xs:selector xpath="Operation"/>
						<xs:field xpath="@Name"/>
					</xs:unique>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="NameSpace" type="IDNameType" use="required">
				<xs:annotation>
					<xs:documentation>子系统权限命名空间</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Operation">
		<xs:annotation>
			<xs:documentation>操作定义</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ObjTypeRef">
					<xs:annotation>
						<xs:documentation>操作所对应的对象类型</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:choice>
							<xs:element name="AllType"/>
							<xs:element name="ObjTypeName" type="IDNameType" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>对象类型名（引用）</xs:documentation>
								</xs:annotation>
								<xs:keyref name="ObjTypeNameRef" refer="ObjTypeNameUnique">
									<xs:selector xpath="."/>
									<xs:field xpath="."/>
								</xs:keyref>
							</xs:element>
						</xs:choice>
					</xs:complexType>
					<xs:unique name="OprObjTypeNameRefUnique">
						<xs:selector xpath="ObjTypeName"/>
						<xs:field xpath="."/>
					</xs:unique>
				</xs:element>
			</xs:sequence>
			<xs:attributeGroup ref="ID_Attr"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ObjType">
		<xs:annotation>
			<xs:documentation>对象类型定义</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice>
				<xs:element name="InputObjName"/>
				<xs:element name="NoObjName"/>
				<xs:element name="ObjNameOption" type="IDNameType" maxOccurs="unbounded"/>
			</xs:choice>
			<xs:attributeGroup ref="ID_Attr"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="OprGroup">
		<xs:annotation>
			<xs:documentation>操作组</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Operation" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="OprGroup" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== wwkkww1983/czmk_proj/CZMK_PROJECT/SecConfig/FEPOfflinePermDefine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by  () -->
<!--Sample XML file generated by XMLSpy v2005 rel. 3 U (http://www.altova.com)-->
<PermDef xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PermDef.xsd" NameSpace="FEP离线">
	<ObjTypeDef>
		<ObjType Name="FEP节点" CreatDate="2010-04-16" Des="工程中一个FEP节点对应的逻辑实体" Creater="张玉国">
			<InputObjName/>
		</ObjType>
	</ObjTypeDef>
	<OprDef>
		<Operation Name="编辑" CreatDate="2010-04-16" Des="FEP内所涵盖逻辑实体的编辑操作" Creater="张玉国">
			<ObjTypeRef>
				<AllType/>
			</ObjTypeRef>
		</Operation>
	</OprDef>
</PermDef>

=== wwkkww1983/czmk_proj/CZMK_PROJECT/SecConfig/MXVOfflinePermDefine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by  () -->
<PermDef xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PermDef.xsd" NameSpace="操作站组态">
	<ObjTypeDef>
		<ObjType Name="HMI节点" CreatDate="2007-04-05" Des="配置了HMI的节点" Creater="洪志兵">
			<InputObjName/>
		</ObjType>
		<ObjType Name="图形管理单元" CreatDate="2007-04-05" Des="图形管理单元" Creater="洪志兵">
			<InputObjName/>
		</ObjType>
		<ObjType Name="资源" CreatDate="2007-04-05" Des="资源" Creater="洪志兵">
			<InputObjName/>
		</ObjType>
		<ObjType Name="图库子目录" CreatDate="2007-04-05" Des="图库子目录" Creater="洪志兵">
			<InputObjName/>
		</ObjType>
	</ObjTypeDef>
	<OprDef>
		<Operation Name="编辑" CreatDate="2007-04-05" Des="" Creater="洪志兵">
			<ObjTypeRef>
				<AllType/>
			</ObjTypeRef>
		</Operation>
	</OprDef>
</PermDef>

=== wwkkww1983/czmk_proj/CZMK_PROJECT/SecConfig/OORTDB_PADef.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by  () -->
<!--Sample XML file generated by XMLSpy v2005 rel. 3 U (http://www.altova.com)-->
<PermDef xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PermDef.xsd" NameSpace="对象库在线">
	<ObjTypeDef>
		<ObjType Name="数据库单元" CreatDate="2006-12-19" Des="数据库单元，包括对象库和历史库等" Creater="谢文虎">
			<InputObjName/>
		</ObjType>
		<ObjType Name="对象" CreatDate="2006-12-19" Des="数据库对象，即点，包括容器对象、子对象" Creater="谢文虎">
			<InputObjName/>
		</ObjType>
		<ObjType Name="模板" CreatDate="2006-12-29" Des="数据库模板" Creater="谢文虎">
			<InputObjName/>
		</ObjType>
	</ObjTypeDef>
	<OprDef>
		<Operation Name="读写" CreatDate="2006-12-19" Des="读写数据库单元、对象或模板" Creater="谢文虎">
			<ObjTypeRef>
				<AllType/>
			</ObjTypeRef>
		</Operation>
	</OprDef>
</PermDef>
